### PR TITLE
feat : Add Dark/light mode switch Toggle Button

### PR DESCRIPTION
**Pull request by Lee-Dongwook**
Add a dark/light mode toggle button to the top right of the Flitter header and write Playwright test code.
스크린샷 2024-12-13 오후 10 30 04

### CODE REVIEW

**Comment by Lee-Dongwook** [comment]
For images like those for GitHub and Discord, I think we need to add alternative images suitable for light mode as well.

**Comment by Moon-DaeSeung** [comment]
Could you take screenshots of the white theme being applied to the /docs and /tutorial pages?
Also, in the header section when switching to white theme, the GitHub and Discord icons are hard to see! We should probably use Tailwind's invert class to reverse the colors when in white theme.
And please include screenshots of the dark theme version of each screen in the PR to check for side effects.

**Comment by Lee-Dongwook** [comment]
I'll make the edits and upload them once I get home since I was out for a while!

**Comment by Moon-DaeSeung** [comment]
you should write in english not korean.

**Comment by Lee-Dongwook** [comment]
These images are previews of the documentation and tutorial in light mode.

docs-dark
docs-light
tutorial-dark
tutorial-lgiht

**Review by Moon-DaeSeung — APPROVED** [review]
GOODGOOD

**Pull request merged**
